# Generated by Django 3.1.7 on 2021-03-10 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=35, verbose_name='Topic Name')),
                ('description', models.CharField(max_length=100, verbose_name='Topic Description')),
                ('is_private', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_owner', to=settings.AUTH_USER_MODEL)),
                ('topic_admins', models.ManyToManyField(related_name='topic_admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
