# Generated by Django 3.1.7 on 2021-03-10 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserProfile',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bio', models.CharField(default=' ', max_length=150)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(default='DisplayNameNotSet', max_length=25)),
                ('image', models.ImageField(default='default_profile_img.png', upload_to='profile')),
            ],
        ),
    ]
