# Generated by Django 3.1.7 on 2021-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('user_profile', '0002_auto_20210310_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuserprofile',
            name='topics_subscribed_to',
            field=models.ManyToManyField(related_name='user_profile', to='topics.Topic'),
        ),
    ]
