# Generated by Django 3.1.7 on 2021-03-10 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=350)),
                ('visible', models.BooleanField(default=True)),
                ('posting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time_created'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('board_name', models.CharField(max_length=25)),
                ('board_description', models.CharField(max_length=100, verbose_name='Board descriptions')),
                ('assoc_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='topics.topic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards_owner', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(related_name='board', to='boards.Post')),
            ],
        ),
    ]
